<?php
$langstat = array 
(
	0=>'Blog Information',
	1=>'Blog name',
	2=>'Message number',
	3=>'created in',
	4=>'to establish the number of days',
	5=>'days',
	6=>'log the number of articles',
	7=>'average daily',
	8=>'return articles',
	9=>'registration number',
	10=>'access to minutes',
	11=>'total number of visits',
	12=>'today to visit',
	13=>'record',
	14=>'Show the last 20 days of the visit to the historical record',
	15=>'Visitors IP',
	16=>'last active time',
	17=>'current line number:',
	18=>'empty',
	19=>'wrong time parameter!',
	20=>'has completed the clean-up of historical data.',
	21=>'counter',
	22=>'Show the overall counter data',
	23=>'year',
	24=>'month',
	25=>'day',
	26=>'previous data',
	27=>'confirm delete',
	28=>'online list',
	29=>'Show visitors IP list'
);

