<?php

$langstat = array
(
    0  => 'Blog Information',
    1  => 'Blog name:',
    2  => 'Guestbook messages:',
    3  => 'Installed at:',
    4  => 'Life span:',
    5  => 'days',
    6  => 'Total articles:',
    7  => 'average daily: ',
    8  => 'Total replies:',
    9  => 'Number of registrations:',
    10 => 'access to minutes',
    11 => 'Total visits:',
    12 => 'Today visits:',
    13 => 'Visits per day',
    14 => 'Show historical visit statistics in last 20 days',
    15 => 'Visitors IP',
    16 => 'Last activity time',
    17 => 'Current line number:',
    18 => 'Empty data before the date: ',
    19 => 'Wrong time parameter!',
    20 => 'Clean-up of historical data have been completed',
    21 => 'Counters',
    22 => 'Show the overall counter data',
    23 => ' - ',
    24 => ' - ',
    25 => '.',
    26 => '',
    27 => 'Confirm delete',
    28 => 'Online visitors',
    29 => 'Show visitors IP list',
);
